//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_DONVI> tb_DONVI { get; set; }
        public virtual DbSet<tb_KHACHHANG> tb_KHACHHANG { get; set; }
        public virtual DbSet<tb_LOAIPHONG> tb_LOAIPHONG { get; set; }
        public virtual DbSet<tb_TANGLAU> tb_TANGLAU { get; set; }
        public virtual DbSet<tb_SANPHAM> tb_SANPHAM { get; set; }
        public virtual DbSet<tb_THIETBI> tb_THIETBI { get; set; }
        public virtual DbSet<tb_PARAM> tb_PARAM { get; set; }
        public virtual DbSet<tb_PHONG> tb_PHONG { get; set; }
        public virtual DbSet<tb_CONGTY> tb_CONGTY { get; set; }
        public virtual DbSet<tb_DATPHONG> tb_DATPHONG { get; set; }
        public virtual DbSet<tb_DATPHONGCHITIET> tb_DATPHONGCHITIET { get; set; }
        public virtual DbSet<tb_DATPHONGSP> tb_DATPHONGSP { get; set; }
        public virtual DbSet<tb_SYS_FUNCTION> tb_SYS_FUNCTION { get; set; }
        public virtual DbSet<tb_SYS_GROUP> tb_SYS_GROUP { get; set; }
        public virtual DbSet<tb_SYS_REPORT> tb_SYS_REPORT { get; set; }
        public virtual DbSet<tb_SYS_ROLE> tb_SYS_ROLE { get; set; }
        public virtual DbSet<tb_SYS_ROLE_REPORT> tb_SYS_ROLE_REPORT { get; set; }
        public virtual DbSet<tb_SYS_USERS> tb_SYS_USERS { get; set; }
        public virtual DbSet<tb_PHONGTB> tb_PHONGTB { get; set; }
        public virtual DbSet<VIEW_SYS_USER_NOTIN_GROUP> VIEW_SYS_USER_NOTIN_GROUP { get; set; }
        public virtual DbSet<VIEW_SYS_USER_IN_GROUP> VIEW_SYS_USER_IN_GROUP { get; set; }
        public virtual DbSet<VIEW_SYS_FUNCTION_ROLE> VIEW_SYS_FUNCTION_ROLE { get; set; }
    
        public virtual ObjectResult<PHIEU_DATPHONG_Result> PHIEU_DATPHONG(Nullable<int> iDDP)
        {
            var iDDPParameter = iDDP.HasValue ?
                new ObjectParameter("IDDP", iDDP) :
                new ObjectParameter("IDDP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PHIEU_DATPHONG_Result>("PHIEU_DATPHONG", iDDPParameter);
        }
    }
}
