//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DATPHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_DATPHONG()
        {
            this.tb_DATPHONGCHITIET = new HashSet<tb_DATPHONGCHITIET>();
            this.tb_DATPHONGSP = new HashSet<tb_DATPHONGSP>();
        }
    
        public int IDDP { get; set; }
        public int IDKHACH { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
        public Nullable<double> SOTIEN { get; set; }
        public Nullable<int> SONGUOI { get; set; }
        public int IDUSER { get; set; }
        public string MACTY { get; set; }
        public string MADVI { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public Nullable<bool> DOAN { get; set; }
        public string GHICHU { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<bool> DISABLED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DATPHONGCHITIET> tb_DATPHONGCHITIET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DATPHONGSP> tb_DATPHONGSP { get; set; }
    }
}
