//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DATPHONGCHITIET
    {
        public int IDDPCT { get; set; }
        public Nullable<int> IDDP { get; set; }
        public Nullable<int> IDPHONG { get; set; }
        public Nullable<int> SONGAYO { get; set; }
        public Nullable<int> DONGIA { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
    
        public virtual tb_DATPHONG tb_DATPHONG { get; set; }
        public virtual tb_PHONG tb_PHONG { get; set; }
    }
}
