//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PHONGTB
    {
        public int IDPHONG { get; set; }
        public int IDTHIETBI { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<bool> DISABLED { get; set; }
        public string TENPHONG { get; set; }
        public string TENTHIETBI { get; set; }
    }
}
