//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_PHONG()
        {
            this.tb_DATPHONGCHITIET = new HashSet<tb_DATPHONGCHITIET>();
            this.tb_DATPHONGSP = new HashSet<tb_DATPHONGSP>();
        }
    
        public int IDPHONG { get; set; }
        public string TENPHONG { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public int IDLAU { get; set; }
        public int IDLOAIPHONG { get; set; }
        public Nullable<bool> DISABLED { get; set; }
        public string TENLAU { get; set; }
        public string TENLOAIPHONG { get; set; }
    
        public virtual tb_LOAIPHONG tb_LOAIPHONG { get; set; }
        public virtual tb_TANGLAU tb_TANGLAU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DATPHONGCHITIET> tb_DATPHONGCHITIET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DATPHONGSP> tb_DATPHONGSP { get; set; }
    }
}
