//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SYS_REPORT
    {
        public int REPORT_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string REPORT_NAME { get; set; }
        public Nullable<bool> VISIBLED { get; set; }
        public Nullable<bool> REPORT_DATETIME { get; set; }
        public Nullable<bool> DATETIME { get; set; }
        public Nullable<bool> MACTY { get; set; }
        public Nullable<bool> MADVI { get; set; }
    }
}
